// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMP1CFHBuqb2EHs3P1F0wLP5NYlexYXHk',
    appId: '1:331548261481:web:94685a9717ce72f99276f8',
    messagingSenderId: '331548261481',
    projectId: 'hystory-app',
    authDomain: 'hystory-app.firebaseapp.com',
    storageBucket: 'hystory-app.appspot.com',
    measurementId: 'G-VM42430SMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtNlDTiMylQ3m_wmVHHwerlYbb8xkm-D4',
    appId: '1:331548261481:android:946136a735f4c88a9276f8',
    messagingSenderId: '331548261481',
    projectId: 'hystory-app',
    storageBucket: 'hystory-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAKKMsoDbzQ0Ft9YoU-9WpF4tVPrNFxAY',
    appId: '1:331548261481:ios:0a87a2972891bd559276f8',
    messagingSenderId: '331548261481',
    projectId: 'hystory-app',
    storageBucket: 'hystory-app.appspot.com',
    iosClientId: '331548261481-ir40encahpbc0oa6mpm2pq99r9fsd4uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.myHistoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAKKMsoDbzQ0Ft9YoU-9WpF4tVPrNFxAY',
    appId: '1:331548261481:ios:0a87a2972891bd559276f8',
    messagingSenderId: '331548261481',
    projectId: 'hystory-app',
    storageBucket: 'hystory-app.appspot.com',
    iosClientId: '331548261481-ir40encahpbc0oa6mpm2pq99r9fsd4uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.myHistoryApp',
  );
}
