// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4BwolYKN_H_E_6y4XRg12VpJs6M_n40U',
    appId: '1:920012027651:web:1e708e52cf89e49c95db36',
    messagingSenderId: '920012027651',
    projectId: 'historyapp-6b230',
    authDomain: 'historyapp-6b230.firebaseapp.com',
    storageBucket: 'historyapp-6b230.appspot.com',
    measurementId: 'G-RC8T4XN8K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdY70-D2HqJgRdBe4W7COOhuEQGYn5iWs',
    appId: '1:920012027651:android:a4cf8ba79f50415c95db36',
    messagingSenderId: '920012027651',
    projectId: 'historyapp-6b230',
    storageBucket: 'historyapp-6b230.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUtwkApkm0JMBiIoBxgBoY7JUfESH83Vc',
    appId: '1:920012027651:ios:7b36fd9d3d71e0b795db36',
    messagingSenderId: '920012027651',
    projectId: 'historyapp-6b230',
    storageBucket: 'historyapp-6b230.appspot.com',
    iosClientId: '920012027651-ubeqtote54075ancmths4l8u5qi8ae1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myHistoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUtwkApkm0JMBiIoBxgBoY7JUfESH83Vc',
    appId: '1:920012027651:ios:7b36fd9d3d71e0b795db36',
    messagingSenderId: '920012027651',
    projectId: 'historyapp-6b230',
    storageBucket: 'historyapp-6b230.appspot.com',
    iosClientId: '920012027651-ubeqtote54075ancmths4l8u5qi8ae1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myHistoryApp',
  );
}
